spring:
  application:
    name: kodiwazi

  datasource:
    url: jdbc:postgresql://localhost:5432/kodiwazi
    username: postgres
    password: your_password

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true